// 产量数据
module.exports = {
	RES_STATUS_SUCCESS: 200,
	RES_STATUS_ERROR: 400,
	RES_STATUS_NOAUTH: 600,
	RES_STATUS_NOLOGIN: 600,

	RES_MESSAGE_SUCCESS: '成功',
	RES_MESSAGE_ERROR: '失败',
	RES_MESSAGE_NOAUTH: '无权限',
	RES_MESSAGE_NOLOGIN: '未登录',
};